version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      MYSQL_DB_NAME: budget
      MYSQL_HOST: db
    env_file:
      - local.env
    ports:
      - '8000:80'
    depends_on:
      - db

  db:
    image: mariadb
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: notasecret

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8080:80'
    depends_on:
      - db
